---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-14.04-chef-11
    provisioner:
      require_chef_omnibus: 11.16.4

suites:
  - name: default
    run_list:
      - recipe[samhain::default]
    attributes:
